### ISSUE TITLE
Change Dim into OnOff?

### ISSUE THREAD

**Issue by killvn** [rogro82/io.homeassistant#1]
All the lights get in the Capabilities "dim", I want more options Capabilities "dim" or "onoff".

**Comment by rogro82** [comment]
Light capabilities are based on the supported_features attribute reported by home-assistant. So if a light has a dim feature in HA it will also have that capability in Homey.

If you want to just want to be able to switch a light on/off then i would suggest either creating a switch in HA or use the custom_component and bind a light entity to the onoff capability.

Something like:
```yaml
homey:
  some_light:
    name: Some light
    capabilities:
      onoff: light.some_light
```
