### ISSUE TITLE
Sensors not updated

### ISSUE THREAD

**Issue by dxfoxd** [rogro82/io.homeassistant#25]
I have a switch that also has 3 sensors. I've created a compound device in configuration.yaml as follows:

```
homey:
  ws8:
    name: WS-8
    icon: meter_power
    capabilities:
       onoff: switch.ws_8_socket_1
       measure_current: sensor.ws_8_current
       measure_power: sensor.ws_8_power
       measure_voltage: sensor.ws_8_voltage

```

The device is found in homey, but the sensors aren't updated. Are these capabilities supported and where to find more information on the supported capabilities?

Thx!

Art
