### ISSUE TITLE
Input Boolean support

### ISSUE THREAD

**Issue by giggo** [rogro82/io.homeassistant#7]
Hi rogro82,
it would be phantastic to show Input Booleans (Home Assistant's kind of virtual devices) as Switches in Homey. Any plans to do so?

Ciao,
gagga

**Comment by giggo** [comment]
This is how they look like in Homeassistant config:

```
input_boolean:
  elternbad:
    name: Elternbad
    initial: off
    icon: mdi:toilet
```
